package com.genairosity.genairositybackend.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;

/**
 * Entity representing a structured curriculum program spanning multiple weeks.
 * Maps to hackathon_teams.genairosity.curriculum table.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "hackathon_teams.genairosity.curriculum")
public class Curriculum {

    /**
     * Unique identifier for each curriculum.
     * Auto-generated by the database.
     */
    @Id
    @Column("curriculum_id")
    private Long curriculumId;

    /**
     * Name of the curriculum program.
     */
    @Column("curriculum_name")
    private String curriculumName;

    /**
     * Description of the curriculum content and objectives.
     */
    @Column("description")
    private String description;

    /**
     * The target qualification of this curriculum, if any.
     */
    @Column("target_qualification")
    private String targetQualification;

    /**
     * Total duration in weeks (typically 12).
     */
    @Column("duration_weeks")
    private Integer durationWeeks;

    /**
     * When the curriculum was created.
     */
    @Column("created_at")
    private LocalDateTime createdAt;

    /**
     * Last update timestamp.
     */
    @Column("updated_at")
    private LocalDateTime updatedAt;

    /**
     * Whether this curriculum is currently active.
     */
    @Column("is_active")
    private Boolean isActive;

    /**
     * Source of the curriculum data.
     */
    @Column("data_source")
    private String dataSource;
}